### ISSUE TITLE
Cannot install libscrc on Python 3.10 on MacOS

### ISSUE THREAD

**Issue by crenwick** [hex-in/libscrc#10]
On MacOS, running python 3.10, `pip install libscrc` returns the following error:

```py
ERROR: Could not find a version that satisfies the requirement libscrc (from versions: none)
ERROR: No matching distribution found for libscrc
```

I have to downgrade to python 3.8 to install libscrc, but works fine on 3.10 on Ubuntu.

**Comment by crenwick** [comment]
I was able to clone this repo to build + install libscrc 1.8 on my python 3.10.3's version of python, so I think this might just be a pip distribution issue.

**Comment by denisbondar** [comment]
I get the exact same error when using the **python:3.10-alpine** docker image:
```
ERROR: Could not find a version that satisfies the requirement libscrc (from versions: none)
ERROR: No matching distribution found for libscrc
```

**Comment by hex-in** [comment]
> On MacOS, running python 3.10, `pip install libscrc` returns the following error:
> 
> ```python
> ERROR: Could not find a version that satisfies the requirement libscrc (from versions: none)
> ERROR: No matching distribution found for libscrc
> ```
> 
> I have to downgrade to python 3.8 to install libscrc, but works fine on 3.10 on Ubuntu.

I fixed it as soon as possible.

**Comment by hex-in** [comment]
> I get the exact same error when using the **python:3.10-alpine** docker image:
> 
> ```
> ERROR: Could not find a version that satisfies the requirement libscrc (from versions: none)
> ERROR: No matching distribution found for libscrc
> ```

Please try again.

**Comment by hex-in** [comment]
> I was able to clone this repo to build + install libscrc 1.8 on my python 3.10.3's version of python, so I think this might just be a pip distribution issue.

Pls try again.

**Comment by denisbondar** [comment]
> Python 3.10 (or 3.9) using Docker container with Alpine (or Debian buster) - **Failed**:
> https://pastebin.com/3vXM6WiY

Sorry. No gcc was installed. Below is a snippet of output after installing gcc. Docker container python:3.10-buster was used:
```
...
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.10 -c src/crcx/_crcxmodule.c -o build/temp.linux-aarch64-cpython-310/src/crcx/_crcxmodule.o
src/crcx/_crcxmodule.c:22:10: fatal error: _crcxtables.h: No such file or directory
   22 | #include "_crcxtables.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
[end of output]
...
```

**Comment by hex-in** [comment]
> > Python 3.10 (or 3.9) using Docker container with Alpine (or Debian buster) - **Failed**:
> > https://pastebin.com/3vXM6WiY
> 
> Sorry. No gcc was installed. Below is a snippet of output after installing gcc. Docker container **python:3.10-buster** was used. When using the **python:3.10-alpine3.15** image, the result is exactly the same.
> 
> ```
> ...
> gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.10 -c src/crcx/_crcxmodule.c -o build/temp.linux-aarch64-cpython-310/src/crcx/_crcxmodule.o
> src/crcx/_crcxmodule.c:22:10: fatal error: _crcxtables.h: No such file or directory
>    22 | #include "_crcxtables.h"
>       |          ^~~~~~~~~~~~~~~
> compilation terminated.
> error: command '/usr/bin/gcc' failed with exit code 1
> [end of output]
> ...
> ```

OK, I'll try my best to solve it. Thank u for ur feedback.

**Comment by cquick01** [comment]
I'm also unable to install libscrc 1.8 with a similar error message about `_crcxtables.h`. I'm running on Ubuntu 22.04 (WSL2).

In case it helps, I've uploaded the full output with errors that I'm seeing to a gist here: https://gist.github.com/cquick01/bd182c57ae203cf79da5a82c2209cf5a

**Comment by pikhovkin** [comment]
> I'm also unable to install libscrc 1.8 with a similar error message about `_crcxtables.h`. I'm running on Ubuntu 22.04 (WSL2).
> 
> In case it helps, I've uploaded the full output with errors that I'm seeing to a gist here: https://gist.github.com/cquick01/bd182c57ae203cf79da5a82c2209cf5a

Same error on Ubuntu 22.04 and Python 3.10.6

**Comment by sunnysolutions** [comment]
> I'm also unable to install libscrc 1.8 with a similar error message about `_crcxtables.h`. I'm running on Ubuntu 22.04 (WSL2).
> 
> In case it helps, I've uploaded the full output with errors that I'm seeing to a gist here: https://gist.github.com/cquick01/bd182c57ae203cf79da5a82c2209cf5a

Same error on Termux on Android 9 and Python 3.10.6
Give it a try by using the github link of the libscrc project

$ pip install git+https://github.com/hex-in/libscrc.git

It worked this way for me!

**Comment by hex-in** [comment]
> I get the exact same error when using the **python:3.10-alpine** docker image:
> 
> ```
> ERROR: Could not find a version that satisfies the requirement libscrc (from versions: none)
> ERROR: No matching distribution found for libscrc
> ```

Pls try again.

**Comment by denisbondar** [comment]
> Pls try again.

Now it's okay! Thank you so much!

**Comment by pikhovkin** [comment]
I'm confirm, now it's ok!

**Comment by pikhovkin** [comment]
a build for `python:3.10.5-slim`  is ok
a build for `python:3.11.5-slim`  is error

```
ERROR: Could not build wheels for libscrc, which is required to install pyproject.toml-based projects
Failed to build libscrc
```

**Comment by TheLavrov** [comment]
I'm trying to use this with Pyscript but because 3.11 does not have wheels I cannot use it.
